from fastapi import APIRouter, HTTPException
from langchain_groq import ChatGroq
from pydantic import BaseModel
import os
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GOOGLE_API_KEY")

Model = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.6,
    api_key=GROQ_API_KEY
)

router = APIRouter()

class DetailedSummaryRequest(BaseModel):
    forecast_3h: float
    forecast_6h: float
    forecast_12h: float
    forecast_24h: float

@router.post("/generate-summary")
async def generate_aqi_summary(payload: DetailedSummaryRequest):
    try:
        prompt = f"""
        You are an advanced environmental AI analyst for an Islamabad Air Quality Dashboard.
        Analyze this full chronological timeline generated by our Machine Learning models:
        - 3 Hours Later Forecast: {payload.forecast_3h}
        - 6 Hours Later Forecast: {payload.forecast_6h}
        - 12 Hours Later Forecast: {payload.forecast_12h}
        - 24 Hours Later Forecast: {payload.forecast_24h}
        
        Write a concise, professional, and highly actionable analysis (max 3-4 sentences). 
        You must specify the predicted trend across these specific intervals (3h, 6h, 12h, and 24h). 
        Tell the user if air quality is improving or deteriorating over the next 24 hours and provide real-world health advice (e.g., outdoor activities safety, mask usage) based on this trend.
        Keep it engaging, friendly, and clear.
        """
        
        ai_message = Model.invoke(prompt)
        response_text = ai_message.content
        
        return {"status": "success", "summary": response_text.strip()}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Gemini Error: {str(e)}")